export const LOADING_RESOURCES = 'LOADING_RESOURCES';
export const GET_RESOURCES = 'GET_RESOURCES';
export const GET_RESOURCES_SUCCESS = 'GET_RESOURCES_SUCCESS';
export const GET_RESOURCES_FAILURE = 'GET_RESOURCES_FAILURE';

export const POSTING_RESOURCE = 'POST_RESOURCE';
export const POST_RESOURCE = 'POST_RESOURCE';
export const POST_RESOURCE_SUCCESS = 'POST_RESOURCE_SUCCESS';
export const POST_RESOURCE_FAILURE = 'POST_RESOURCE_FAILURE';

export const DELETING_RESOURCE = 'DELETE_RESOURCE';
export const DELETE_RESOURCE = 'DELETE_RESOURCE';
export const DELETE_RESOURCE_SUCCESS = 'DELETE_RESOURCES_SUCCESS';
export const DELETE_RESOURCE_FAILURE = 'DELETE_RESOURCES_FAILURE';

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SET_PAGINATION = 'SET_PAGINATION';

